### ISSUE TITLE
End of Time - Nozdormu

### ISSUE THREAD

**Issue by Jenovas** [Jenovas/Atlantiss4.3#2]
You can find Echo of Nozdormu in every zone. In every zone he should tell players something about the zone.

After some research it seems there are 3 entries of Nozdormu in End of Time:
1. 54867 - Emerald Dragonshrine (Echo of Tyrande) and Azure Dragonshrine (Echo of Jaina)
2. 54751 - Entryway of Time and Bronze Dragonshrine (Murozond)
3. 54476 - Ruby Dragonshrine (Echo of Sylvanas) and Obsidian Dragonshrine (Echo of Baine)

Tasks to do:
1. Add the missing texts / sounds
2. Make sure the right Nozdormu is in the right zone, if not delete and add creature
3. Make sure all the models are proper

Also after killing Murozond Nozdormu should show up and talk with players.

**Comment by Jenovas** [comment]
Example how to add texts in DB

-- Image Of Nozdormu - EnterJainaZone
DELETE FROM creature_text WHERE entry IN (54867);
INSERT INTO creature_text(entry, groupid, id, TEXT, TYPE, LANGUAGE, probability, emote, sound) VALUES
(54867, 0, 0, "This is all that is left of the Blue Dragonshrine. A great battle shattered the timeways leading out of this forsaken place. 
You must reconstruct the fragments strewn across the ground and defeat the trapped spirit to proceed.", 12, 0, 100, 0, 25957);

How to understand the above
https://trinitycore.atlassian.net/wiki/display/tc/creature_text

Sounds can be found on Wowhead.
Search for NPC, click on sounds, click on the sound and you should be taken to a webpage like this -
http://www.wowhead.com/sound=25957
The number after "sound=" is the number that you need to add in the SQL under the key "sound".

**Comment by Jenovas** [comment]
Echo of Nozdormu in every zone I think has a different entry, please check to make sure the right NPC has the right texts / sounds.

**Comment by Jenovas** [comment]
i did some research and it seems there are 3 entrie of Nozdormu:
1. 54867 - Emerald Dragonshrine (Echo of Tyrande) and Azure Dragonshrine (Echo of Jaina)
2. 54751 - Entryway of Time  and Bronze Dragonshrine (Murozond)
3. 54476 - Ruby Dragonshrine (Echo of Sylvanas) and Obsidian Dragonshrine (Echo of Baine)

**Comment by Piklo** [comment]
```sql
-- second Nozdormu sentence, Sylvanas zone
INSERT INTO creature_text(`entry`, `groupid`, `id`, `TEXT`, `TYPE`, `LANGUAGE`, `probability`, `emote`, `sound`) VALUES
(54476 , 1, 0, "You must give peace to these lands if you are to face Murozond.", 12, 0, 100, 0, 25959);
-- second Nozdormu sentence, Baine zone
INSERT INTO creature_text(`entry`, `groupid`, `id`, `TEXT`, `TYPE`, `LANGUAGE`, `probability`, `emote`, `sound`) VALUES
(54751 , 1, 0, "You must give peace to these lands if you are to face Murozond.", 12, 0, 100, 0, 25959);
-- nozdormu modelid
UPDATE creature_template SET modelid1 = 38754 WHERE `entry` IN (54867, 54751, 54476);
```

rest texts / sounds seems to be ok
