### ISSUE TITLE
End of Time - Echo of Baine - Ruptured Ground

### ISSUE THREAD

**Issue by Jenovas** [Jenovas/Atlantiss4.3#4]
The NPCs before Baine cast Rupture Ground - 102124 this summons 54566.
For some weird reason 54566 is Archmage Lan'dalock instead of being a trigger.

NPC 54566 should be http://www.wowhead.com/npc=54566/ruptured-ground

1. Please fix the creature_template (check maybe Trinity Core has a proper entry).
2. Add SAI / BAI to the NPC and make it cast 102128 on itself as soon as it is summoned.

**Comment by xmesaj2** [comment]
Rather safe to delete & insert new proper template, no spawns in `creature`
