### ISSUE TITLE
End of Time - Echo of Tyrande - texts

### ISSUE THREAD

**Issue by Piklo** [Jenovas/Atlantiss4.3#6]
some texts shouldn't be yells

for example
https://youtu.be/NUCPjpvGCI4?t=15m42s
![image](https://cloud.githubusercontent.com/assets/16057987/26549956/d288c662-447b-11e7-9a4e-23ef02e7d148.png)

Tasks to do:
1. check type for Tyrande texts

Tyrande texts are well showed here
http://wow.gamepedia.com/Echo_of_Tyrande

You may also need to check the text types for other bosses

**Comment by TranceAccount** [comment]
This one is only for the one you posted
`UPDATE creature_text SET type = 12 WHERE entry IN (54544); -- Echo of Tyrande now says this instead of yelling`
